### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by CsatiZoltan** [jakubcerveny/hogtess#1]
`make -C build` resulted
```
[ 50%] Building CXX object CMakeFiles/hogtess.dir/render.cpp.o
In file included from /home/zoli/Downloads/hogtess-master/render.cpp:13:0:
/home/zoli/Downloads/hogtess-master/render.hpp:8:21: fatal error: QGLWidget: No such file or directory
 #include <QGLWidget>
                     ^
compilation terminated.
```
Cmake configuration showed
```
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- using /home/zoli/Downloads/hogtess-master/cmake/file2cpp as file2cpp
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.6") 
Qt QTOPENGL library not found.
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so (Required is at least version "4.0") 
-- Found GLM: /usr/include  
-- Configuring done
-- Generating done
```

**Comment by jakubcerveny** [comment]
Try installing libqt4-opengl-dev.

**Comment by jakubcerveny** [comment]
(If it works I'll add it to the instructions)

**Comment by CsatiZoltan** [comment]
That library was needed. However, I now get other errors. See the attached error log.
[errorMessage.txt](https://github.com/jakubcerveny/hogtess/files/2126978/errorMessage.txt)

**Comment by jakubcerveny** [comment]
What version of libGLM do you have? (Run dpkg -l 'libqt4-opengl-dev'). Mine is 0.9.9.

The line "glm::perspective(45.0, aspect, 0.001, 100.0);" should probably be changed to "glm::perspective(glm::radians(45.0f), float(aspect), 0.001f, 100.0f);"

**Comment by CsatiZoltan** [comment]
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libqt4-opengl- 4:4.8.5+git1 amd64        Qt 4 OpenGL library development f
```

**Comment by jakubcerveny** [comment]
Oh, sorry, that was supposed to be `dpkg -l 'libglm-dev'`

**Comment by CsatiZoltan** [comment]
I have version 0.9.5.1-1. Correcting that line solved the problem. Now I need the mfem.hpp header. I know that this project needs mfem. Is the mfem.hpp file needed only? Or other files from MFEM too? Where to copy the mfem files (which directory)?

**Comment by jakubcerveny** [comment]
You need to download (or clone) MFEM and build its serial version (make serial). The path to MFEM is specified in CMakeLists.txt (MFEM_PATH). The default assumes that the directories "mfem" and "hogtess" share the same parent directory.

**Comment by CsatiZoltan** [comment]
Thank you. Almost done. Failed in the last phase:
```
[ 60%] Building CXX object CMakeFiles/hogtess.dir/main.cpp.o
[ 70%] Building CXX object CMakeFiles/hogtess.dir/moc_main.cxx.o
[ 80%] Building CXX object CMakeFiles/hogtess.dir/moc_render.cxx.o
[ 90%] Building CXX object CMakeFiles/hogtess.dir/shaders/shape.glsl.cpp.o
[100%] Building CXX object CMakeFiles/hogtess.dir/shaders/surface.glsl.cpp.o
Linking CXX executable hogtess
CMakeFiles/hogtess.dir/render.cpp.o: In function `RenderWidget::paintGL()':
/home/zoli/Downloads/hogtess-master/render.cpp:237: undefined reference to `glPatchParameteri'
collect2: error: ld returned 1 exit status
```

**Comment by jakubcerveny** [comment]
glPatchParameteri is the OpenGL4 function that's needed for GPU tesselation. Looks like you have an older version of OpenGL. What system do you have? What do you get when you run `glxinfo | grep version`? (you may need to install glxinfo first).

**Comment by CsatiZoltan** [comment]
I have (the quite old) Ubuntu 14.04.
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
OpenGL version string: 2.1 Mesa 10.1.3
OpenGL shading language version string: 1.20```

**Comment by jakubcerveny** [comment]
I'm afraid you would have to upgrade to at least Ubuntu 16.04 to make this work. OpenGL 4.0 or higher is required for hogtess.

**Comment by CsatiZoltan** [comment]
I will check it and report next week on my laptop having 16.04.

**Comment by CsatiZoltan** [comment]
On Ubuntu 16.04, I managed to compile just as written in the README file. Then I ran
```
 ./build/hogtess data/mesh.4 data/sln.4
```
which resulted
```
Loading mesh: data/mesh.4
Loading solution: data/sln.4
Polynomial order: 4
OpenGL version: 3.0 Mesa 17.2.8, renderer: llvmpipe (LLVM 5.0, 256 bits)
terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenGL version 4.0 or higher is required to run this program.
Aborted (core dumped)
```
This is a runtime error, apparently my OpenGL version is not high enough. I will update it later. Thanks for the compilation advice.

**Comment by jakubcerveny** [comment]
Sometimes multiple OpenGL profiles are supported. Grepping glxinfo to "version" will reveal what profiles are available and you may be able to switch them with an environment variable (as described in the README).

**Comment by CsatiZoltan** [comment]
`glxinfo` reports version 3.3. Using that additional flag:
```
OpenGL version: 4.0 (Core Profile) Mesa 17.2.8, renderer: llvmpipe (LLVM 5.0, 256 bits)
terminate called after throwing an instance of 'ShaderError'
  what():  Error compiling shader:
0:1(10): error: GLSL 4.00 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.50, 3.30, 1.00 ES, and 3.00 ES

Aborted (core dumped)
```

**Comment by jakubcerveny** [comment]
I'm afraid that's it then, the tesselation shader (introduced in GLSL 4.00)
cannot be compiled on your system.
